/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.deltastateonline.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PersonalLib extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonalLib\",\"namespace\":\"com.deltastateonline.model\",\"fields\":[{\"name\":\"Movies\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Movie\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"duration\",\"type\":\"int\"},{\"name\":\"genre\",\"type\":\"int\"},{\"name\":\"director\",\"type\":\"string\"},{\"name\":\"actors\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Actor\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"gender\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<com.deltastateonline.model.Movie> Movies;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PersonalLib() {}

  /**
   * All-args constructor.
   */
  public PersonalLib(java.util.List<com.deltastateonline.model.Movie> Movies) {
    this.Movies = Movies;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Movies;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Movies = (java.util.List<com.deltastateonline.model.Movie>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Movies' field.
   */
  public java.util.List<com.deltastateonline.model.Movie> getMovies() {
    return Movies;
  }

  /**
   * Sets the value of the 'Movies' field.
   * @param value the value to set.
   */
  public void setMovies(java.util.List<com.deltastateonline.model.Movie> value) {
    this.Movies = value;
  }

  /** Creates a new PersonalLib RecordBuilder */
  public static com.deltastateonline.model.PersonalLib.Builder newBuilder() {
    return new com.deltastateonline.model.PersonalLib.Builder();
  }
  
  /** Creates a new PersonalLib RecordBuilder by copying an existing Builder */
  public static com.deltastateonline.model.PersonalLib.Builder newBuilder(com.deltastateonline.model.PersonalLib.Builder other) {
    return new com.deltastateonline.model.PersonalLib.Builder(other);
  }
  
  /** Creates a new PersonalLib RecordBuilder by copying an existing PersonalLib instance */
  public static com.deltastateonline.model.PersonalLib.Builder newBuilder(com.deltastateonline.model.PersonalLib other) {
    return new com.deltastateonline.model.PersonalLib.Builder(other);
  }
  
  /**
   * RecordBuilder for PersonalLib instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonalLib>
    implements org.apache.avro.data.RecordBuilder<PersonalLib> {

    private java.util.List<com.deltastateonline.model.Movie> Movies;

    /** Creates a new Builder */
    private Builder() {
      super(com.deltastateonline.model.PersonalLib.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.deltastateonline.model.PersonalLib.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Movies)) {
        this.Movies = data().deepCopy(fields()[0].schema(), other.Movies);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PersonalLib instance */
    private Builder(com.deltastateonline.model.PersonalLib other) {
            super(com.deltastateonline.model.PersonalLib.SCHEMA$);
      if (isValidValue(fields()[0], other.Movies)) {
        this.Movies = data().deepCopy(fields()[0].schema(), other.Movies);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'Movies' field */
    public java.util.List<com.deltastateonline.model.Movie> getMovies() {
      return Movies;
    }
    
    /** Sets the value of the 'Movies' field */
    public com.deltastateonline.model.PersonalLib.Builder setMovies(java.util.List<com.deltastateonline.model.Movie> value) {
      validate(fields()[0], value);
      this.Movies = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Movies' field has been set */
    public boolean hasMovies() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Movies' field */
    public com.deltastateonline.model.PersonalLib.Builder clearMovies() {
      Movies = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public PersonalLib build() {
      try {
        PersonalLib record = new PersonalLib();
        record.Movies = fieldSetFlags()[0] ? this.Movies : (java.util.List<com.deltastateonline.model.Movie>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
